title: Welcome to my data journey
description: I’m a full-stack Data Engineer obsessed with ETL processes and visualizations. You can find here projects I’ve enjoyed making and challenged myself on. Feel free to comment and share. I’m open to advice for improvement. I’m also open to new opportunities so let’s work together!

theme: jekyll-theme-cayman
